easy_admin:
    user:
        display_name: true
        display_avatar: false

    site_name: 'Job Alert <em style="font-size: 80%;"></em>'
    design:
      assets:
        css: ['admin/custom_backend.css']
        js:
          - 'https://unpkg.com/snarkdown@1.2.2/dist/snarkdown.umd.js'
          - 'js/custom_backend.js'
      menu:
        - {entity: 'User', icon: 'user',target: '_self',default: true }
        - {entity: 'Ville', icon: 'dashboard',target: '_self',default: true }

        - label: 'CV'
          icon: 'newspaper-o'
          children:
            - {entity: 'Experience', icon: 'tag'}
            - {entity: 'Skill', icon: 'tag'}
            - {entity: 'Training' , icon: 'tag'}

        - label: 'job'
          icon: 'th-list'
          children:
            - {entity: 'Offre', icon: 'inbox'}
            - {entity: 'Category', icon: 'inbox'}
            - {entity: 'typeEmploi', icon: 'inbox'}




    entities:
        User:
          class: App\Entity\User
          form:
          new:
            form_options: { validation_groups: ['Default', 'Customer'] }
          edit:
            title:  'Edit user'

          help: 'Global message displayed in all views'

          show:
            title: '%%entity_label%% (#%%entity_id%%)'

          search:

          list:
            fields:
              - id
              - { property: 'firstName', type: 'text' }
              - { property: 'lastName', type: 'text' }
              - { property: 'phone', type: 'tel' }
              - { property: 'email', label: 'email', type: 'email' , type_options: { trim: true }}

            max_results: 30
            title: '%%entity_label%% listing'
            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }



        Offre:
          class: App\Entity\Offre
          list:
            fields:
              - id
              - { property: 'nomEntreprise', type: 'text' }
              - { property: 'IntiuleDePost', type: 'text' }
              - { property: 'lieu', type: 'text' }
              - { property: 'taille', type: 'text' }
            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }



        Experience:
          class: App\Entity\Experience
          list:
            fields:
              - id
              - { property: 'JobTitle', type: 'text' }
              - { property: 'companyName', type: 'text' }
              - { property: 'ville', type: 'text' }
              - { property: 'description', type: 'text' }

            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }

        Skill:
          class: App\Entity\Skill
          list:
            fields:
              - id
              - { property: 'skille', type: 'text' }
              - { property: 'expertise', type: 'text' }

            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }


        Training:
          class: App\Entity\Training
          list:
            fields:
              - id
              - { property: 'diplome', type: 'text' }
              - { property: 'ecole', type: 'text' }
              - { property: 'domaine', type: 'text' }
              - { property: 'ville', type: 'text' }

            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }

        Ville:
          class: App\Entity\Ville
          list:
              fields:
                - id
                - { property: 'ville', type: 'text' }
              actions:
                - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
                - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
                - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }

        Category:
          class: App\Entity\Category
          list:
            fields:
              - id
              - { property: 'nom', type: 'text' }
            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }


        typeEmploi:
          class: App\Entity\typeEmploi
          list:
            fields:
              - id
              - { property: 'nom', type: 'text' }
            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }






