easy_admin:
    user:
        display_name: true
        display_avatar: false

    site_name: 'Job Alert <em style="font-size: 80%;"></em>'
    design:
      assets:
          css:
            - 'assert/css/admin.css'



    list:
      title: 'List of %%entity_label%%'
      actions: ['show']

    entities:
        User:
          class: App\Entity\User
          export_path: '%kernel.project_dir/var/export/user'
          password_encoding: { algorithm: 'bcrypt', cost: 12 }
          label: users
          help: 'list of all candidat'
          list:
              help: 'do not feed!'
              fields:
                - id
                - { property: 'firstName', trans: true, domain: 'messages',icon: 'user' }
                - { property: 'lastName',icon: 'user' }
                - { property: 'phone',type: 'tel'  }
                - { property: 'email', type: 'email' }
                - roles




              actions:
                  - { name: 'edit', icon: 'pencil', label: 'Edit' }
                  - { name: 'show', icon: 'info-circle', label: 'show' }
                  - { name: 'delete', label: 'delete' }




        Offre:
          class: App\Entity\Offre
        Location:
          class: App\Entity\Location
        Experience:
          class: App\Entity\Experience
        Skill:
          class: App\Entity\Skill
        Training:
          class: App\Entity\Training
        Ville:
          class: App\Entity\Ville


        Category:
          class: App\Entity\Category
          help: 'Global message displayed in all views'
          list:
            max_results:
            title: '%%entity_label%% listing'
          show:
            max_results:
            title: '%%entity_label%% (#%%entity_id%%)'
        typeEmploi:

          class: App\Entity\typeEmploi





