easy_admin:
    user:
        display_name: true
        display_avatar: false

    site_name: 'Job Alert <em style="font-size: 80%;"></em>'
    design:
      assets:
        css: ['admin/custom_backend.css']
      menu:
        - {entity: 'User', icon: 'user',target: '_self',default: true }
        - {entity: 'Ville', icon: 'blog',target: '_self',default: true }

        - label: 'CV'
          icon: 'newspaper-o'
          children:
            - {entity: 'Experience', icon: 'tag'}
            - {entity: 'Location', icon: 'tag'}
            - {entity: 'Skill', icon: 'tag'}
            - {entity: 'Training' , icon: 'tag'}

        - label: 'Offre'
          icon: 'newspaper-o'
          children:
            - {entity: 'Category', icon: 'inbox'}
            - {entity: 'typeEmploi', icon: 'inbox'}








    entities:
        User:
          class: App\Entity\User
          form:
          new:
            form_options: { validation_groups: ['Default', 'Customer'] }
          edit:
            title:  'Edit user'

          help: 'Global message displayed in all views'

          show:
            title: '%%entity_label%% (#%%entity_id%%)'

          search:

          list:
            fields:
              - id
              - { property: 'firstName', type: 'text' }
              - { property: 'lastName', type: 'text' }
              - { property: 'phone', type: 'tel' }
              - { property: 'email', label: 'email', type: 'email' , type_options: { trim: true }}

            max_results: 30
            title: '%%entity_label%% listing'
            actions:
              - {name: 'edit' , icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete' , icon: 'trash', label: false, css_class: 'btn btn-danger'}
              - { name: 'show', icon: 'info-circle', label: '',css_class: 'btn btn-success' }



        Offre:
          class: App\Entity\Offre
        Location:
          class: App\Entity\Location
        Experience:
          class: App\Entity\Experience
        Skill:
          class: App\Entity\Skill
        Training:
          class: App\Entity\Training
        Ville:
          class: App\Entity\Ville


        Category:
          class: App\Entity\Category
        typeEmploi:
          class: App\Entity\typeEmploi





